import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/layout/Navbar";
import "./globals.css";
import ComponentesFuncionais from "@/components/layout/ComponentesFuncionais";
import ReRenderizacao from "@/components/layout/ReRenderizacao";
import UseRef from "@/components/layout/UseRef";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        <Navbar />
        <ComponentesFuncionais />
        <ReRenderizacao />
        <UseRef />
        {children}
      </body>
    </html>
  );
}


